### ISSUE TITLE
Error: thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by Boscop** [watchexec/watchexec#108]
Any idea why `watchexec -r docker-compose run foo_test cargo test -v` doesn't work? https://paste.centos.org/view/ac6e5713#46qgVYtB5pvakPbpdUp5hYCNjd1u5mFw

Also it doesn't work with `--`:
```
> watchexec -r -- docker-compose run foo_test cargo test -v
Error: 
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)
```

**Comment by Mange** [comment]
Does `watchexec -r docker-compose run foo_test /bin/bash -c "echo foo"` work?

That could perhaps isolate between `docker-compose` and your Rust app.

I recently did #102 in order to support `docker-compose` and friends, so perhaps it's related. Did this work previously, or did you try it for the first time recently?

**Comment by passcod** [comment]
I'm sorry, I can't see that paste. Also, is this on Windows?

In that case could you try building using `RUSTFLAGS="-C link-args=/STACK:16777216" cargo install --force watchexec` (if using MSVC) or `RUSTFLAGS="-C link-args=-Wl,--stack,16777216" cargo install --force watchexec` (if using GNU).

**Comment by jmgao** [comment]
Possibly fixed by https://github.com/watchexec/watchexec/pull/111?

**Comment by passcod** [comment]
Oh, yes, or at least that may uncover the real problem

**Comment by passcod** [comment]
#111 has been released now.
