### ISSUE TITLE
Running watchexec in daemon background mode

### ISSUE THREAD

**Issue by hgezim** [watchexec/watchexec#124]
How do I run watchexec in daemon or background mode?

Alternatively, an official docker image would be awesome to have!

**Comment by passcod** [comment]
```
watchexec --options... &
```

Usually does the trick. What's the usecase for daemon mode or the docker image?

**Comment by hgezim** [comment]
I have a process running in a container that I want restarted when some files change. Having watchexec in Docker makes that easier to manage.

**Comment by passcod** [comment]
Sure, I can see that.

I'm just confused about the utility of an official image here. Unless Docker images have fundamentally changed since the last time I looked, wouldn't an official watchexec image lock you into whatever base image we use?

For the daemon mode, it feels kinda outside the scope; a supervisor (or a bash entrypoint that launches a bunch of children with `&`) would be responsible for that. It's not a hard proposition to add a base form in (there's even a neat crate that makes it pretty magically simple); I'm more trying to think through if that should even be in scope here.
