### ISSUE TITLE
How to get run command **on** file changed

### ISSUE THREAD

**Issue by nikitavoloboev** [watchexec/watchexec#137]
If I want to run say `node <file.js>` on any files that were modified. I can't figure out how to do that. I can `watchexec --exts js node ..` where `..` is any of the files that were changed.

Can I do this?

**Comment by passcod** [comment]
Not directly at the moment, but that would be an interesting feature! Right now, the `$WATCHEXEC_*_PATH` variables (described in the readme) are your best bet: you can write a little script that reads those and then runs node on them.

**Comment by nikitavoloboev** [comment]
A bit confused how I would use this variable in the command invocation. Can you give an example?

**Comment by JakobGM** [comment]
> @nikitavoloboev A bit confused how I would use this variable in the command invocation. Can you give an example?

I just tested out this feature, here is what I have found.
Start by running the following commands in your terminal:

```
$ cd ~/tmp
$ watchexec --exts py --verbose 'echo $WATCHEXEC_WRITTEN_PATH >> changed_python_files.txt'
```

After having modified `~/tmp/first_file_edited_twice.py` twice and `~/tmp/second_file_edited_once.py` once, the content of `~/tmp/changed_python_files` is as follows:

```
/home/jakobgm/tmp/first_file_edited_twice.py
/home/jakobgm/tmp/first_file_edited_twice.py
/home/jakobgm/tmp/second_file_edited_once.py
```

Some tips:

* Use single quotes around the command you want to be executed by `watchexec`, otherwise `$WATCHEXEC_*_PATH` will be interpolated at once, instead of everytime a file is modified.
* Use `dirname $WATCHEXEC_WRITTEN_PATH` and `basename $WATCHEXEC_WRITTEN_PATH` in order retrieve pertinent information from the modified path.

Hopes this helps!

**Comment by passcod** [comment]
Just not going to do this, it's too out of scope. The new modes from `--emit-events-to` may help writing helpers for this; otherwise this is something that should go to a build system like make, just, or tooling like checkexec.
