### ISSUE TITLE
watchexec npx webpack --help can not run

### ISSUE THREAD

**Issue by laoshaw** [watchexec/watchexec#152]
it will give out the help for watchexec instead of for webpack, which is unexpected

try `watchexec -- npx webpack --help`  will give help info for webpack, however it will keep giving the info repeatedly.

**Comment by passcod** [comment]
The first _is_ expected, due to ambiguity as to how arguments are parsed. The solution is to either use `--` or quote the entire command.

I don't understand why you'd want to call `npx webpack --help` in watchexec. What does that benefit from reloading / file watching? What's the usecase?

Additionally, I can't reproduce. What directory are you running this command from?

**Comment by laoshaw** [comment]
it's just one simple webpack command "watchexec npx webpack --config webpack.config.js", I used '--help' for simplicity as both are running with --options

use `watchexec "npx webpack --config webpack.config.js"` will keep running the commands continuously even nothing changed, this is not what I wanted.

however if I do `ls dist/* | entr npx webpack --config webpack.config.js" it worked fine, it runs once, and will run again only when files under dist/ changed.

this is a hello world for webpack, nothing fancy.

**Comment by passcod** [comment]
What directory are you running this command from?

Watchexec will watch all of the descendants minus some default ignores, so if you're expecting it to magically watch just `dist/` without you telling it, it won't. The _most likely reason_ why your command is repeating is that `npx webpack --help` is touching _something_ in the current directory or children and thus retriggering ad infinitum. Again, I cannot reproduce when I run in a random empty directory, so this is most likely due to _where_ you're running this from.

Additionally, you should run with `--verbose` and it will tell you what it's seeing.

**Comment by laoshaw** [comment]
--verbose says `*** Received SIGCHLD`

My wild guess is that, "entr" remembers the file before the command it runs, to avoid dead loops(output a new file, trigger entr, which output updated file), basically if a file is modified by the command behind entr, entr will not re-run the command.

watchexec will re-run the command as long as any files under watch is modified, in this case, 'webpack' will update the timestamp of its output files under dist/ each time, thus a loop forever occured.

the correct way in this case, is to ignore dist/ directory, i.e. `watchexec -i dist/ "npx webpack --config webpack.config.js "`, this makes sense, but I'm surprised 'entr' somehow can handle it.

I will remember ignoring output(e.g. dist/) files produced by the commands watchexec  runs.

still, if watchexec can ignore -- from the command behind it it will be nice.

**Comment by passcod** [comment]
Yeah, that's #40.
