### ISSUE TITLE
Unable to use generated environment variables with alerter/ osacript to create a workflow

### ISSUE THREAD

**Issue by AnirvanB** [watchexec/watchexec#155]
`Watchexec` is a great tool, thanks for bringing it us! 💯 👍  

I'm trying to create a workflow wherein the app runs as a _daemon_. It is supposed to trigger a notification alert when files are added/ removed/ updated from a certain folder that I wish to monitor. For this I intend to use [alerter](https://github.com/vjeantet/alerter)/ osacript. 

Unable to get this right so far :(

My attempt:

``` watchexec -- "echo $WATCHEXEC_CREATED_PATH | alerter -title "WatchExec" -subtitle "change detected" -closeLabel No -actions Yes  -sound glass"```

Please let me know what am I doing wrong?

**Comment by passcod** [comment]
Given I can't test this as I'm not on mac (your link doesn't work btw), what is it doing wrong?

But also at first glance you're using double quotes here and not escaping anything, this is a bash question not a watchexec problem... try

```
watchexec -- 'echo $WATCHEXEC_CREATED_PATH | alerter -title "WatchExec" -subtitle "change detected" -closeLabel No -actions Yes -sound glass'
```

**Comment by AnirvanB** [comment]
Thanks @passcod  for pointing out the broken link, I have updated it now.  
 

> Q - "what is it doing wrong?"

The notification popup (alterer) was getting triggered fine, but it was not showing the  environment variables details in the popup body, which was expected.

> Solution 

The code that you provided worked. Double quotes was the issue. Can you please elaborate on why the double quotes wouldn't work, the part you mentioned _"not escaping anything"_. I'm a script kiddie not a dev. 😬

Thanks again!

**Comment by passcod** [comment]
Sure, okay. So, this is a shell thing, at least for bash/zsh type shells. Might differ for other syntaxes of shells, but I'm going to ignore that here. There's a few things happening here:

- **quotes in quotes**. so, quoted strings are _delimited by_ single or double quotes. that is `"this is a string"`. but what happens if you have quotes inside the string? This will be invalid: `"not "a string"` and this is actually three strings, one unquoted in the middle: `"first quoted "unquoted" second quoted"`. furthermore the three strings are (somewhat unintuitively) `first quoted `, `unquoted`, ` second quoted`... notice the leading and trailing spaces! So, to embed quotes in strings they need escaping: this is a single string: `"a \"quoted\" string"` that works out to `a "quoted" string`.
- **single in double, double in single.** Escaping is tedious, and you have two quote types available, so a quick solution instead of escaping double quotes inside a double quoted string is to use single quotes, or vice versa. These are both a single string: `'a "quoted" string'` and `"a 'quoted' string"`, evaluating to `a "quoted" string` and `a 'quoted' string` respectively.
- **single is raw, double is interpolated.** The difference between single and double is that double quoted strings are _interpolated_. What that means is that variables and some other things called expansions (but, confusingly, not all expansions... play around) are expanded immediately when they're found in a double quoted string, but **not** if they're found in a single quoted one. So this: `"hello $USER"` will result in `hello yourusername` but `'hello $USER'` results in `hello $USER` as is.
- and finally **nesting is often mindbendy especially with indirection.** Here you have several layers of shells, which reveals itself when you do this kind of thing. First layer is where you're typing, second layer is what watchexec runs. When you say `watchexec -- "echo $WATCHEXEC_CREATED_PATH"` the double quotes are in the context of the first layer, so the interpolation runs immediately, that variable doesn't exist, so this works out to the same as calling `watchexec -- echo`... and now watchexec runs, something changes, it runs `echo` with no arguments which just outputs a newline. When instead you say `watchexec -- 'echo $WATCHEXEC_CREATED_PATH'` the single quotes prevent the interpolation, so you're really giving that to watchexec, and when watchexec goes it runs `echo $WATCHEXEC_CREATED_PATH` in a shell, that's layer two, the variable is available, and it does what you expect.

Hope that's not too confusing, you should probably find bash resources to learn the syntax a bit more if you want to.
