### ISSUE TITLE
watchexec not working with json files

### ISSUE THREAD

**Issue by theghostyced** [watchexec/watchexec#164]
## Description

I am trying to run a translate script whenever my json file changes, using watchexec to watch the folder doesnt seem to work.. More references below

## Terminal Output
<img width="788" alt="Screenshot 2020-07-20 at 19 40 46" src="https://user-images.githubusercontent.com/28215750/87973822-02a3a780-cac1-11ea-8fa6-2eaebc93c5cb.png">

## Shell Script
<img width="921" alt="Screenshot 2020-07-20 at 19 41 45" src="https://user-images.githubusercontent.com/28215750/87973877-14854a80-cac1-11ea-9dbf-e34cb7e84578.png">

## JSON file
<img width="848" alt="Screenshot 2020-07-20 at 19 42 22" src="https://user-images.githubusercontent.com/28215750/87973922-28c94780-cac1-11ea-89ce-9ad585ab8681.png">

Am i doing something wrong? Any help would be most appreciated 🙏

**Comment by passcod** [comment]
From your output, watchexec is working fine, and all the errors are coming from your script.

**Comment by passcod** [comment]
Now, _which_ script. In this case, the one you show.

Still not a watchexec bug.

This is a shell thing. Shells do expansions. Expansion outputs result in (most times) space-separated arguments. In this case, the culprit is the `*` expansions.

You write:

```bash
watchexec -v --exts json -f ./locales/* -w ./locales/*/** ...
```

what that translates to, _before watchexec even runs_ is something like:

```bash
watchexec -v --exts json -f ./locales/en -w ./locales/en/abacus.json ./locales/en/account.json ...
```

watchexec runs this, and (correctly, as far as it knows) interprets that as:

- Flag: `-v`
- Option: `--exts` = `json`
- Option: `-f` = `./locales/en`
- Option: `-w` = `./locales/en/abacus.json`
- Positional argument (command to run) = `./locales/en/account.json ...`

So it tries to run `locales/en/account.json` as a shell script. Boom!

So, a couple of things:

1. You want to quote the argument to `-f`.
2. You do not need to write `folder/*/**` when giving an argument to `-w`, because watchexec _already_ recurses into directories.

**Comment by passcod** [comment]
As a side note, pasting screenshots instead of text logs is pretty annoying! I can't copy-paste from a screenshot, so it's harder to reproduce.

**Comment by theghostyced** [comment]
> As a side note, pasting screenshots instead of text logs is pretty annoying! I can't copy-paste from a screenshot, so it's harder to reproduce.

Apologies for this, thought dropping a screenshot would be much more faster to visualize than typing the error. Will take that into account going forward

Thanks for the help and explanation that solved my issue 🙏
