### ISSUE TITLE
-w detects change only once

### ISSUE THREAD

**Issue by abitrolly** [watchexec/watchexec#179]
When using `-w` option to monitor a single file, `watchexe` fires only twice - once on start, and then on first modification. No matter how much times the file is modified afterwards, these modifications are not detected.

To reproduce, create some `reqq` file (mine is non-empty). Run watch exec. See that it triggers.

    watchexec -w reqq -v -- ./sendreq.sh reqq

Run `vim reqq`. Save the file and see `watchexec` triggers. Save once again and see that nothing happens.

    watchexec 1.14.1

Fedora 33.

**Comment by passcod** [comment]
That's because of how vim (and most editors, it's a common way to prevent corruption) saves files. It doesn't. It creates a new one and moves it in place. As a result, you're watching the first file, get the deleting event, and then nothing more happens because what you're watching is not there anymore.

You can observe the behaviour by instead running this:

```
watchexec -w file -- 'env | grep WATCHEXEC`
```

When saving with vim, you'll get this:

```
WATCHEXEC_REMOVED_PATH=/path/to/file
WATCHEXEC_META_CHANGED_PATH=/path/to/file
```

If you instead use `touch file`, you'll see this:

```
WATCHEXEC_WRITTEN_PATH=/path/to/file
WATCHEXEC_META_CHANGED_PATH=/path/to/file
```

and you'll be able to receive more events.

---

The workaround is to watch the containing directory, and filter off all events but for the file you want.

**Comment by abitrolly** [comment]
I had to use `--force-poll` together with `-w`. If `watchexec` is able to detect that watched file name changed, I don't see why it can't implement the logic of tracking when a new file is created with the same name.
