### ISSUE TITLE
WATCHEXEC_RENAMED_PATH: paths order has changed

### ISSUE THREAD

**Issue by ngirard** [watchexec/watchexec#262]
**What used to happen**
Using Watchexec 0.15.1, `WATCHEXEC_RENAMED_PATH` predictably ordered `new_path` before `old_path`:
```
WATCHEXEC_RENAMED_PATH=<new_path>:<old_path>
```

**What happens now**
Now, using v0.18.7.
When `touch a.md` then executing these two commands in cycle:
```sh
mv a.md b.md
mv b.md a.md
```
`WATCHEXEC_RENAMED_PATH` always contains `a.md:b.md`

**Comment by passcod** [comment]
It may have happened to appear like that, but order was actually not defined. Indeed, in systematic testing across platforms, order sometimes randomly changed, which is why actually predictable ordering (byte sort) was put in place. There's also no guarantee, due to debouncing and the nature of filesystems and event updates, that you always get both the new and old paths together, or even exactly two paths (you may get zero, one, three...) in `WATCHEXEC_RENAMED_PATH`.

This ordering was mentioned in the release notes for 1.18.0. The paths are also deduplicated since 1.18.6, as you know.

For a practical example, consider issuing this command:

```
$ mv {a,b}.md; mv {b,a}.md
```

or, watching folder `c` only:

```
$ mv c/a.md .
$ mv a.md c/
```

(on inotify Linux, the second one may actually result in a file create event instead of a half rename)

and what happens if (watching folder `c` only again):

```
$ mv c/{a,b}.md .
```

**Comment by ngirard** [comment]
Thanks for the thorough explanation. Indeed, I should have re-read the release notes before issuing this.
This might be an opportunity to improve the docs for the CLI, by adding e.g. 
```
Within these environment variables, multiple paths are sorted (with binary ordering) and separated by `:` on Unix and `;` on Windows.
```
right after the envvar table in https://github.com/watchexec/watchexec/blob/main/cli/README.md

I'm not submitting a PR because I'm sure you'll know better how to phrase this.
Feel free to close this issue whenever you want.

Cheers!

**Comment by ngirard** [comment]
Great addition to the docs ! Thanks !
