### ISSUE TITLE
Allow filters from stdin

### ISSUE THREAD

**Issue by lammermann** [watchexec/watchexec#281]
Thanks a lot for this great tool. It's helping me a lot in my daily work.

I would like to be able to specify filters from stdin like so: `ls | watchexec --stdin echo 'some file changed'` 

This would allow me use my own scripts to figure out which files should be observed. For example i would love to refresh my browser every time any of the files included in my html (css, scripts, images, etc) changed. Then i could run `my_get_all_dependencies_script.sh localfile.html | watchexec --stdin reload_browser.sh localfile.html`

A possible alternative would be a configuration file (i've seen feature requests for that) since i could generate this file first and then run watchexec. However this would be a little inconvenient because the syntax of a config file is more complex than a simple list of files/patterns.

Would you consider adding this feature?

**Comment by passcod** [comment]
I don't think I'll be adding reading stdin and interpreting it as filters because that seems a bit too specific.

There's a few existing options here, though.

- We do already have support for a kind of configuration for, with the `@argfile` pattern. Process your file list to be valid watchexec arguments, write that to a file or use bash `<()`, and call it like `watchexec @thefile -- command ...`

- The `tagged` filterer mode is not very documented but it enables a `-F` option that you can use to load a filter file directly — one filter per line, in tagged syntax.

- Depending on platform you may be able to use /dev/stdin for these paths and pipe things in anyway.

**Comment by lammermann** [comment]
It seems as if my use case is already covered by tagged filter. However i could not find much about how to use it (did a quick search through the git repo). Would it be used like this:

A file with dependencies (`dependencies.txt`)

```
/path/to/stylesheet.css
/path/to/img/**.png
```

And than on cli `watchexec -F dependencies.txt -- load_browser.sh localfile.html`? 
Or is it `watchexec @dependencies.txt -- load_browser.sh localfile.html`?

Sorry if I'm asking something too obvious. Tagged filters is a feature I don't know much about.

**Comment by passcod** [comment]
You'll need to do some processing in both cases.

Tagged filter syntax is documented here: https://docs.rs/watchexec/2.0.0-pre.14/watchexec/filter/tagged/struct.TaggedFilterer.html Note that it's an early and unstable feature which likely has rough edges, and requires the `WATCHEXEC_FILTERER` environment variable to be set to `tagged`.

The `@file` syntax however is stable, and only contains regular CLI arguments, so you'd want to produce eg:

```
--filter=/path/to/stylesheet.css
--filter=/path/to/img/**.png
```

and then call `watchexec @file --otherflags -- command ...`

**Comment by passcod** [comment]
Closing. Re-open or comment if there's still an issue here
