### ISSUE TITLE
Option to exit when stdin closes - to help avoid orphaned process

### ISSUE THREAD

**Issue by michaeljones** [watchexec/watchexec#440]
**Is your feature request related to a problem? Please describe.**

*I've been using `cargo watch` so I'll refer to that but I've made the issue here as it isn't cargo related functionality*

When running `cargo watch` as a subprocess as a 'watcher' in an Elixir/Phoenix development server setup, the default behaviour is that the `cargo watch` subprocess is orphaned and keeps running after the development server is shutdown. 

It is hard to guarantee that the parent process (dev server) shuts the child process (cargo watch) down as the parent can be killed quite abruptly and not left the time to run any clean up code. 

- Elixir help docs about the general issue: https://hexdocs.pm/elixir/1.14.2/Port.html#module-zombie-operating-system-processes

**Describe the solution you'd like**

According to Elixir docs, the easiest way to avoid this is for `cargo watch` to monitor its own standard input and shut itself down when standard input ends. This means that the parent process can open standard input, though do nothing with it, and when the parent process is shutdown then standard input ends and the `cargo watch` process ends.

- Webpack has `watchOptions.stdin` which can be enabled: https://webpack.js.org/configuration/watch/#watchoptionsstdin
- Esbuild had it added by the creator of Elixir to manage this issue with Phoenix adopted esbuild as its go-to bunder: https://github.com/evanw/esbuild/pull/1449
 
**Describe alternatives you've considered**

I'm not sure of any alternatives.

If proposing a new CLI option, option names you think would fit.

Some ideas:

- `--end-with-stdin`
- `--watch-stdin`
- `--auto-close`

I guess `--watch-stdin` would be best but perhaps confusing given the name of this project so I imagine something else would ideally be chosen.

**Additional context**

The Elixir help docs provide a shell script that can act as a middle layer and handle the situation. It creates more noise in the set up though so it would be great if `watchexec` supported it directly but I realise it might not be a high priority given the work around.

**Comment by passcod** [comment]
Besides being a breaking change functionally, do you think there would be a significant downside to just making this the default behaviour?

**Comment by michaeljones** [comment]
I know nothing about the code base. I have an beginner-to-intermediate level of Rust experience. Is it worth me having a shot at a PR for this? I have no great urgency for it but I also don't like burdening maintainers with requests though reviewing PRs for merging is also a burden. Hard path to walk :)

**Comment by passcod** [comment]
You decide! I can describe the things to implement at high level.

For background, the architecture is:
- sources gather events
- events are debounced and filtered
- event(s) make it through the debounce/filters and trigger an "action"
- `on_action` handler is called, returning an `Outcome`
- outcome is processed into managing the command that watchexec is running
  - outcome can also be to exit
- when a command is started, the `on_pre_spawn` and `on_post_spawn` handlers are called
- commands are also a source of events, so e.g. "command has finished" is handled by `on_action`

And this is the startup sequence:
- init config sets basic immutable facts about the runtime
- runtime starts:
  - source workers start, and are passed their runtime config
  - action worker starts, and is passed its runtime config
- (unless `--postpone` is given) a synthetic event is injected to kickstart things

Implementing this, there's two parts:

1. in the library:
   - add a worker for "sourcing" handle events. looking at the [signal source worker](https://github.com/watchexec/watchexec/blob/main/crates/lib/src/signal/source.rs) is probably easiest to get started here.
   - because we don't always want to look at handles, and just to be flexible, add [runtime config](https://github.com/watchexec/watchexec/blob/main/crates/lib/src/config.rs#L33) for the handle "source", specifying a list of I/O handles to watch, for example.
   - for convenience, probably add [a method on the runtime config](https://github.com/watchexec/watchexec/blob/main/crates/lib/src/config.rs#L46) which configures it for stdin, as the most common usecase.
   - because watchexec is reconfigurable, in the worker you'll need to react to changes in the list of handles being watched. this isn't super complicated, look at how the [fs worker does it](https://github.com/watchexec/watchexec/blob/main/crates/lib/src/fs.rs#L171).
   - as this is something I hadn't foreseen, you'll need to [add to the event tag enum](https://github.com/watchexec/watchexec/blob/main/crates/lib/src/event.rs#L42).
   - in consequence, to be complete you should [add support to the "tagged filterer"](https://github.com/watchexec/watchexec/blob/main/crates/filterer/tagged/src/parse.rs), but as this is added work and things will work fine without, feel free to skip it

2. the cli:
	- add the option to the [args](https://github.com/watchexec/watchexec/blob/main/crates/cli/src/args.rs)
	- add to the [runtime config](https://github.com/watchexec/watchexec/blob/main/crates/cli/src/config/runtime.rs#L22) when the option is present
	- process events containing the corresponding tag [in the action handler](https://github.com/watchexec/watchexec/blob/main/crates/cli/src/config/runtime.rs#L84)
	- document the option in the [manual page](https://github.com/watchexec/watchexec/blob/main/doc/watchexec.1.ronn)

I'm happy to get one or multiple PRs for any of this, if you choose to take a stab :)

**Comment by michaeljones** [comment]
Thank you for taking the time to share that. I'll have a look and see how I get on and keep you updated with any progress.

**Comment by michaeljones** [comment]
> * because we don't always want to look at handles, and just to be flexible, add [runtime config](https://github.com/watchexec/watchexec/blob/main/crates/lib/src/config.rs#L33) for the handle "source", specifying a list of I/O handles to watch, for example.

I'm not sure what the best representation for a generic IO handle is in Rust? It seems that stdin can be converted to a platform specific handle type. `Fd` or `Handle`. Is that the idea? I guess without some kind of generic treatment then it'll remain as a feature for just stdin.

Though I'm not 100% sure how the feature would be used for other handles. I guess watchexec can be used as a library and people might want to respond to events of some file handle closing due to the file being moved or something? Not sure.

**Comment by passcod** [comment]
True enough. Perhaps let's instead make it a `Keyboard` source and start off as a boolean to watch for the stdin stream closing.

**Comment by michaeljones** [comment]
I've posted a first approach in #449. It actually doesn't work properly but I'm not confident in the preferred way to resolve that. Happy to change any and all of it. No rush to review, just happy to have tried to help.

**Comment by passcod** [comment]
I'll close this when I cut a watchexec release with it. Thank you for your contribution!

**Comment by michaeljones** [comment]
Thanks for making it a good contributing experience. I appreciate you taking the time.

**Comment by passcod** [comment]
That was released in 1.21.0 in january.
