### ISSUE TITLE
TUI stopped working in 1.24.0

### ISSUE THREAD

**Issue by LucasPickering** [watchexec/watchexec#743]
I use watchexec for TUI development, and after updating to 1.24.0 it stopped working. When I run `watchexec -- cargo run` now, it compiles then hangs with no output shown. On 1.23.0, the TUI would take over the screen as expected. I downgraded to confirm the probably started with 1.24.0

- OS version: MacOS 14.2.1

I think the easiest way to reproduce this is to run one of [ratatui](https://github.com/ratatui-org/ratatui)'s examples.

- Clone the ratatui repo
- `watchexec -- cargo run --example block`

Here's the log output from that command on 1.24.0:

```
{"timestamp":"2023-12-21T02:16:48.184528Z","level":"INFO","fields":{"message":"running main loop"},"target":"watchexec_cli"}
{"timestamp":"2023-12-21T02:16:48.184551Z","level":"DEBUG","fields":{"message":"handing over main task handle"},"target":"watchexec::watchexec"}
{"timestamp":"2023-12-21T02:16:48.184565Z","level":"DEBUG","fields":{"message":"starting main task"},"target":"watchexec::watchexec"}
{"timestamp":"2023-12-21T02:16:48.184609Z","level":"DEBUG","fields":{"message":"launching unix signal worker"},"target":"watchexec::sources::signal"}
{"timestamp":"2023-12-21T02:16:48.184660Z","level":"DEBUG","fields":{"message":"launching filesystem worker"},"target":"watchexec::sources::fs"}
{"timestamp":"2023-12-21T02:16:48.184663Z","level":"DEBUG","fields":{"message":"running action handler"},"target":"watchexec::action::worker"}
{"timestamp":"2023-12-21T02:16:48.184665Z","level":"DEBUG","fields":{"message":"creating new watcher","kind":"Native"},"target":"watchexec::sources::fs"}
{"timestamp":"2023-12-21T02:16:48.184723Z","level":"DEBUG","fields":{"message":"applying changes to the watcher","to_watch":"[WatchedPath(\"/Users/lucas/git/ratatui\")]","to_drop":"[]"},"target":"watchexec::sources::fs"}
{"timestamp":"2023-12-21T02:16:48.184801Z","level":"DEBUG","fields":{"message":"take control of new tasks"},"target":"watchexec::action::worker"}
{"timestamp":"2023-12-21T02:16:48.184806Z","level":"DEBUG","fields":{"message":"action handler finished"},"target":"watchexec::action::worker"}
```

**Comment by passcod** [comment]
Maybe like in #742, I wonder, does it work with `--no-process-group`?

**Comment by LucasPickering** [comment]
@passcod Yep, it works with `--no-process-group`

**Comment by passcod** [comment]
Yeah, that's due to a fix in how process grouping was implemented. It used to do setsid, but was always meant to do sedpgid, as the signal handling was predicated on it being setpgid, and it matches the Windows API better.

Unfortunately it also turns out that the setsid behaviour spuriously allowed *some* (but not all!) things like TUIs. You'll have to use that option from now on, and take care to do signal handling and child reaping if needed.

In future watchexec will add another option to allocate and run in a pty, which may help even more for the TUI case, and on Linux another option will spawn in cgroups when available, which will also help for non-pgid/sid process grouping cases.

**Comment by LucasPickering** [comment]
Ah, thanks for the explanation
