### ISSUE TITLE
 Can't pass argument containing a whitespace to underlying command without quoting the entire command

### ISSUE THREAD

**Issue by keras** [watchexec/watchexec#82]
See difference in following:

```
$ watchexec /usr/bin/printf '[%s]' foo 'bar baz'
[foo][bar][baz]
^C
```
vs
```
$ /usr/bin/printf '[%s]' foo 'bar baz'                                                                                                                          
[foo][bar baz]
```

**Comment by passcod** [comment]
Note however that #87 was fixed, so this issue is partially resolved using `--no-shell` instead.

**Comment by raxod502** [comment]
Shouldn't quotes be added only when more than one positional argument is passed to `watchexec`?

Ideally, the interface of `watchexec` would make it more obvious whether or not quotes are going to be added (imagine that I want to run a binary with spaces in its name—then whether it works depends on whether I pass any arguments), but it's probably too late to fix that.

**Comment by passcod** [comment]
It still makes for incompatible rules even with the "more than one arg".
E.g.

    $ watchexec echo \`echo 'bar  baz'\`

That would be

    ["echo", "`echo", "bar  baz'`"]

And would make

    sh -c "echo `echo 'bar  baz\'`'"

And that would now fail.

There's more examples, but: without parsing the input (unfeasible) it's
hard to cover all cases correctly.

**Comment by passcod** [comment]
It still makes for incompatible rules even with the "more than one arg".
E.g.

    $ watchexec echo \`echo 'bar  baz'\`

That would be

    ["echo", "`echo", "bar  baz'`"]

And would make

    sh -c "echo `echo 'bar  baz\'`'"

And that would now fail.

There's more examples, but: without parsing the input (unfeasible) it's
hard to cover all cases correctly.

**Comment by raxod502** [comment]
I think this whole thing could be cleared up if we simply disallowed multiple arguments unless `-n` is passed.

Anyone who expects `watchexec` to be able to do something sensible when given multiple strings and told to "make them into a shell command" (in some way that differs from running a program named by the first string and passing the remaining strings as command-line arguments) has very weird expectations, in my opinion.

This is the same situation as Python's `subprocess` module has. You can pass either a string, which is run via `sh -c`, or you can pass a list of the program name and the command-line arguments. There is no option to pass a list of strings and have them somehow concatenated into a shell command, because that use case simply doesn't make sense.

[I arrived at the above conclusions after looking more clearly at the `-n` flag, and now believe that my previous comment is pretty much just wrong and silly.]

**Comment by passcod** [comment]
Unfortunately, backwards compatibility.

Something to think about for 2.0, maybe.

**Comment by passcod** [comment]
Reclassifying as a documentation issue rather than a bug: I don't really see any viable universal fix but clearly documenting the behaviour should alleviate confusion.

**Comment by frangio** [comment]
What about using additional arguments to sh and concatenating `"$@"` in the command string, as so:

```
sh -c '/usr/bin/printf "$@"' sh '[%s]' foo 'bar baz' 
```

**Comment by passcod** [comment]
That could maybe solve simple cases, but not e.g. `'echo a; echo b'`, <code>echo \`echo 'bar  baz'`</code>...

**Comment by keras** [comment]
How about adding an option for disabling the intermediate shell and just calling the command without any unnecessary shell magic?

Ps. IMHO this should be the default mode. The user can always add his own shell to the command line if needed. But I do understand that the default is not probably possible to change at this point, but just saying...

**Comment by passcod** [comment]
That already exists, it's `-n`

**Comment by ngirard** [comment]
I'm late in the party and still semi-sleepy, but would `/usr/bin/env -S <shell> -c <command>` help here ?

Since env `-S` option would split the command ?

**Comment by passcod** [comment]
That's a GNU env option.

**Comment by ngirard** [comment]
> That's a GNU env option.

Do you mean to say that it's not shipped with MacOS ?

**Comment by passcod** [comment]
Seems BSD env has `-S`. But, well, I can't rely on `env` on Windows, and it's not present at all in Busybox `env`. Also relying on an external tool is... not great?

**Comment by ngirard** [comment]
> it's not present at all in Busybox `env`.

Ah, good to know !

> Also relying on an external tool is... not great?

Maybe. Anyway, I wasn't trying to push for `env`. 

And regarding OP's needs, for anything beyong the trivial cases, I'd suggest having watchexec executing a script, rather than a complex one-liner.

**Comment by raxod502** [comment]
Yes, I don't think there's any need to invoke `env` as an external process. All the `-S` option does is split on whitespace, which can equally easily be done with a standard library function in Rust. But either way, the issue here is fundamentally that the existing semantics are unintuitive, and we can't change them without breaking backwards compatibility. With that in mind, there's nothing to do here but wait until the next major version bump and then fix the semantics to what people would more naturally expect.

**Comment by passcod** [comment]
Look, fundamentally, I'm really going to need more evidence on the "it's unintuitive" thing. So far there's, what, four people in this thread?

Let's look at alternative and similar tools:

- standard linux `watch`? Uses shell by default, has an option to not
- `nodemon`? Has a fairly different invocation pattern, but sure supports shellisms in its `-x` option, which is how you run arbitrary commands
- `entr`? Uses exec by default, shell by option
- `fswatch` and `inotifywait` don't directly run commands

Feel free to add more, or to idk, perform a study or survey of the userbase to figure it out. I'm simply not going to change default behaviour on something as fundamental as this without significant evidence that it _is_ indeed less intuitive than the proposed alternative for a significant portion of users.

**Comment by raxod502** [comment]
Ah! I think perhaps I've miscommunicated. The fact that you use the shell by default, with an option to not, is totally great! The specific thing I think is unintuitive is that multiple arguments are allowed _even when you're using the shell_. So basically we have three cases:

Case 1 is using a single argument with a shell (works as expected):

```
% watchexec "echo 'foo  bar'"
foo  bar
```

Case 2 is using multiple arguments without a shell (works as expected):

```
% watchexec -n echo 'foo  bar'  
foo  bar
```

Case 3 is using multiple arguments _with_ a shell (unintuitive; why is this allowed?):

```
% watchexec echo 'foo  bar'
foo bar
```

Standard Linux `watch` shares the case 3 behavior with `watchexec`, while `entr` disallows it (only the first argument is evaluated when using a shell):

```
% ls | entr -s echo "foo  bar"
entr: -s requires commands to be formatted as a single argument
```

I'd argue that standard Linux `watch` got it wrong, being an older utility, while `entr` has the behavior correct. What do you think about adjusting `watchexec` in the next release to match the behavior of `entr` rather than that of `watch`?

**Comment by passcod** [comment]
My argument hasn't changed: it's such a core part that I still need more than just a few people saying it's unintuitive. I would rather not change it to find that everyone _else_ hates it.

As comparison: I have good evidence that everyone does hate the ignores system, also a core part. There's been a dozen different issues reported over the years, plenty of confusion about it either directly creating problems or exacerbating them. So yeah, that's gonna go. It's complicated and will take a lot to basically replace from the ground up, but it eventually will.

I don't nearly have the same level of discontent with this. All up, maybe four people? Over three years? And you already have an option to switch it. Do you want _an option_ to switch behaviour to "disallow multiple args when using shell, but allow them with -n"? Or look, config files are gonna land soon, so you could switch your local default, would that be enough?
