### ISSUE TITLE
UNC paths break CMD commands

### ISSUE THREAD

**Issue by silver886** [watchexec/watchexec#830]
The transition of adopting UNC paths breaks CMD commands on Windows.
This is first seen at v2.1.0.

- watchexec version: v2.1.0 & v2.1.1
- Windows OS build: 22631.3527

```console
watchexec --shell=pwsh -vvv --log-file C:\v2.0.0.log pwd
[Running: pwd]

Path
----
C:\working-directory

[Command was successful]
```

```console
watchexec --shell=pwsh -vvv --log-file C:\v2.1.0.log pwd
[Running: pwd]

Path
----
Microsoft.PowerShell.Core\FileSystem::\\?\C:\working-directory

[Command was successful]
```

```console
watchexec --shell=pwsh -vvv --log-file C:\v2.1.1.log pwd
[Running: pwd]

Path
----
Microsoft.PowerShell.Core\FileSystem::\\?\C:\working-directory

[Command was successful]
```

[v2.0.0.log](https://github.com/watchexec/watchexec/files/15235631/v2.0.0.log)
[v2.1.0.log](https://github.com/watchexec/watchexec/files/15235632/v2.1.0.log)
[v2.1.1.log](https://github.com/watchexec/watchexec/files/15235633/v2.1.1.log)

**Comment by passcod** [comment]
Can you explain the bug a little more? I see three successful runs here

**Comment by silver886** [comment]
The path before v2.0.0 is `C:\working-directory` and the path after v2.1.0 is `\\?\C:\working-directory`.
The latter one caused CMD use default Windows directory.

```console
watchexec --shell=cmd -vvv pwd 
[Running: pwd]
'\\?\C:\working-directory'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
/c/Windows
[Command was successful]
```

The behavior is totally different from v2.0.0.

```console
watchexec --shell=cmd -vvv pwd
[Running: pwd]
/c/working-directory
[Command was successful]
```

**Comment by passcod** [comment]
I see. Is this a problem with anything else than CMD? I'm tempted to special-case CMD to translate UNC paths for it specifically, but leave UNCs for other things (like pwsh etc)

**Comment by silver886** [comment]
I think we need to translate UNCs for all shells on Windows since many programs, such as npm, are using CMD internally.

**Comment by lboulard** [comment]
> I see. Is this a problem with anything else than CMD? I'm tempted to special-case CMD to translate UNC paths for it specifically, but leave UNCs for other things (like pwsh etc)

Hello,

UNC paths are not made for external program to consume. Please use regular Windows path.
I stay on release 2.0.0 because watchexec is 100% broken on windows since release 2.1.0.

Thanks.

**Comment by passcod** [comment]
Cool. Make a PR.

**Comment by W1M0R** [comment]
I use watchexec with just, and the change to UNC paths is also breaking my tasks: https://github.com/casey/just/issues/1167

```pwsh
❯ watchexec --version
watchexec 2.1.2 (2cc7743 2024-07-02) +pid1
commit-hash: 2cc7743677580ec55c71d46d1fc2e8cf51a83a23
commit-date: 2024-07-02
build-date: 2024-07-02
release: 2.1.2
features: default,pid1
```

If UNC paths make sense in general, it would be helpful if a flag could disable the use of unc paths, e.g. `--no-unc`.

**Comment by passcod** [comment]
I don't have any time to work on Watchexec at the moment, but would accept a PR to revert that change / disable UNC for everyone.

**Comment by passcod** [comment]
Released in 2.2.0

**Comment by confor** [comment]
this release fixes the usage of most software installed through package managers, since tools like `npm`, `pip`, `scoop` etc always install a _shim_ to a folder in `%PATH%` which is a `.bat`/`.cmd` file that couldn't be run before. i can also now use `watchexec make`, which is huge.

i greatly appreciate dropping unc paths. this has fixed a serious pain point for me.

**Comment by ravicious** [comment]
I couldn't get watchexec to work with Go within a Windows VM running through Parallels on macOS. My setup was that I had a macOS directory shared to the Windows VM available under `Z:\my-directory`. The problem was that watchexec would set the working dir for the command to something like `\\?\UNC\Mac\my-directory\` which broke the Go compiler.

I fixed this by passing `--workdir $PWD.ProviderPath` to watchexec. `$PWD.ProviderPath` can be replaced with other means of providing the current directory. What matters is that the Go command was executed with `Z:\my-directory` as the working directory.

**Comment by passcod** [comment]
Haaaate windows. I'll see what I can do here.
