### ISSUE TITLE
Sometimes the child process isn't killed properly (here with node-sass) on restart

### ISSUE THREAD

**Issue by tcurdt** [watchexec/watchexec#84]
This is on macOS 10.13.5 with version 1.8.6

I have a built script
```
#!/bin/sh

echo "building start"
#node-sass scss/screen.scss > static/css/screen.css
echo "building stop"
```
Running it with `watchexec --verbose -w scss ./build.sh` works as expected. I can see the output of start and stop. As soon as I comment in the call to `node-sass` it behaves like this:

```
$ watchexec --verbose -w scss ./build.sh
*** Loaded "/Users/tcurdt/.gitignore"
*** Adding ignore: "**/.DS_Store"
*** Adding ignore: "*.pyc"
*** Adding ignore: "*.swp"
*** Adding ignore: "**/.git/**"
*** Adding ignore: "**/.hg/**"
*** Adding ignore: "**/.svn/**"
*** glob converted to regex: Glob { glob: "**/.git/**", re: "(?-u)^(?:/?|.*/)\\.git(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('g'), Literal('i'), Literal('t'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**/.hg/**", re: "(?-u)^(?:/?|.*/)\\.hg(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('h'), Literal('g'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**/.svn/**", re: "(?-u)^(?:/?|.*/)\\.svn(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('s'), Literal('v'), Literal('n'), RecursiveSuffix]) }
*** built glob set; 0 literals, 1 basenames, 2 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 3 regexes
*** Watching "/Users/tcurdt/foo/themes/tcurdt/scss"
*** Assembled command "sh" "-c" "./build.sh"
*** Waiting for filesystem activity
building start
*** Received SIGCHLD

<change something on disk>

*** Path updated: PathOp { path: "/Users/tcurdt/foo/themes/tcurdt/scss/main.scss", op: Some(WRITE), cookie: None }
*** Waiting for process to exit...
```
Calling the script directly or as `sh -c "./build.sh"` does work fine.
So to me it seems like `node-sass` is getting called but never exits. Question is why.
The only difference I see in the process env is

```
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHLVL=3
```
vs
```
SHLVL=2
```
I realize that this is probably a `node-sass` problem but I just want to make sure I don't miss an obvious angle. Any pointers?

**Comment by passcod** [comment]
[SIGCHLD](http://man7.org/linux/man-pages/man7/signal.7.html) is received. That usually means the child (your build script) has terminated. However, [if that's not the case](https://github.com/mattgreen/watchexec/blob/master/src/process.rs#L87-L90), watchexec can get stuck waiting for another event (which should but here clearly doesn't come). Essentially in my reading watchexec thinks the child is terminating, and thus doesn't further try to terminate, and because the child is _not_ communicating further, it gets stuck there. 

There are three scenarios I see could happen, although it is pretty odd how it only happens within watchexec:

- the build script receives a SIGSTOP (or SIGTSTP). That would cause it to further emit a SIGCHLD, but the expectation here is that a SIGCONT would be sent to the build script at some later time to unpause it.
- watchexec receives a SIGCHLD from some other source, or from the build script but not because the script stopped, or some other way, and therefore watchexec thinks the child is terminating when it's really not.
- node-sass and/or bash/dash/sh crashes so completely that watchexec receives a SIGCHLD but somehow Linux still thinks the build script is alive when it's not. Perhaps a zombie process would do this.

I have no further insight on why or what could be happening, but that's my interpretation of what is going on. To investigate further I'd suggest opening htop and looking at the state of watchexec and its children.

**Comment by tcurdt** [comment]
@passcod Thanks for your thoughts.

What I can see is that the process of `node-sass` is still sticking around.
```
23935 tcurdt     32   0 4197M  7160 ?  0.0  0.1  0:00.62    │     └─ -bash
25816 tcurdt     32   0 4186M  1220 ?  0.0  0.0  0:00.00    │        └─ sh watch.sh
25817 tcurdt     40   0 4217M  6184 ?  0.0  0.1  0:00.01    │           └─ watchexec -w scss ./build.sh
25818 tcurdt     32   0 4177M  1212 ?  0.0  0.0  0:00.00    │              └─ /bin/sh ./build.sh
25819 tcurdt     17   0 4327M 23344 ?  0.0  0.3  0:00.32    │                 └─ node-sass
```
So in that sense the waiting and thereby being stuck kind of makes sense. 
The big questions is why there is a SIGCHLD received and when the process is still there.

I tried trapping the signals in the `build.sh` but I don't see anything special either.
So my guess is that `node-sass` switched into another mode of operation - I just don't understand what is causing it in this scenario.

I will also open an issue over at `node-sass` to see what they say.

**Comment by passcod** [comment]
Can you try with cargo watch v4.0.3? Or any other rust program that can run arbitrary commands? (Making one just for this could be done, but certainly more time-consuming than in node or python.)

Cargo watch 4.0.3 is the last version that implemented its process handling logic itself, versions 5 onwards instead delegate to watchexec itself, so not very useful.

To install that version in particular: `cargo install cargo-watch --version 4.0.3`. (If you already have it, you might need `--force`.)

You'll need to add a file named `Cargo.toml` to the same directory just so it doesn't complain about not being in a Cargo project, and the options are different, but it should provide a data point at least.

Err, actually this only works if you _can_ use cargo to install rust programs, sorry if that's not the case.

**Comment by tcurdt** [comment]
@passcod bingo!

```
$ cargo-watch watch -w scss -s ./build.sh
```

Works just fine, too!

**Comment by passcod** [comment]
I mean, it's a good confirmation at least, but I wouldn't rely specifically on cargo watch v4 forever. I moved to basing it on watchexec for many bugs/reasons. (If you need, nodemon likely works just as well.)

It's late here but I'll look at this more tomorrow.

**Comment by passcod** [comment]
This seems fixed, as per my testing. Re-open if it still happens with the latest watchexec.
